"""Metric explanations for Lynx Utilities Analysis."""

from __future__ import annotations
from lynx_utilities.models import MetricExplanation

METRIC_EXPLANATIONS: dict[str, MetricExplanation] = {}

def _add(key, full_name, description, why_used, formula, category):
    METRIC_EXPLANATIONS[key] = MetricExplanation(key=key, full_name=full_name, description=description,
                                                  why_used=why_used, formula=formula, category=category)

# Valuation
_add("pe_trailing", "Price-to-Earnings Ratio (TTM)", "Compares stock price to trailing 12-month earnings per share.", "Primary valuation anchor for regulated utilities since earnings are stable and recurring. Regulated names typically trade 14-20x with a ~5-10% premium to the market in constructive regimes.", "P/E = Price / EPS (TTM)", "valuation")
_add("pb_ratio", "Price-to-Book Ratio", "Compares stock price to book value per share.", "Book value is a reasonable proxy for rate base on regulated utilities. P/B of 1.7-2.2x is typical for high-quality regulated names reflecting the market's premium on rate-base growth.", "P/B = Price / Book Value per Share", "valuation")
_add("ps_ratio", "Price-to-Sales Ratio", "Compares stock price to revenue per share.", "Less informative for utilities given mix of pass-through fuel costs. Useful for cross-checking merchant IPPs with volatile earnings.", "P/S = Market Cap / Revenue", "valuation")
_add("p_fcf", "Price-to-Free Cash Flow", "Compares market cap to free cash flow.", "Often negative or volatile at rate-base-growth utilities because capex frequently exceeds OCF. Meaningful only for mature, cash-harvest utilities and YieldCos.", "P/FCF = Market Cap / Free Cash Flow", "valuation")
_add("ev_ebitda", "Enterprise Value / EBITDA", "Capital-structure-neutral valuation.", "Preferred cross-company multiple for utilities given heavy leverage. Regulated utilities 9-12x, IPPs 6-9x, water 13-17x.", "EV/EBITDA = (Market Cap + Debt - Cash) / EBITDA", "valuation")
_add("ev_revenue", "Enterprise Value / Revenue", "Compares enterprise value to revenue.", "Distorted by pass-through fuel and purchased-power cost recovery. Use only when comparing very similar business models.", "EV/Revenue = EV / Revenue", "valuation")
_add("peg_ratio", "PEG Ratio", "P/E adjusted by growth rate.", "Less useful on utilities given low single-digit EPS growth. A PEG <2 is considered reasonable for utilities (vs <1 for growth sectors).", "PEG = P/E / Annual EPS Growth Rate", "valuation")
_add("dividend_yield", "Dividend Yield", "Annual dividend as percentage of price.", "Central utility valuation metric. Regulated 3-5%, YieldCos 4-7%, water 2-3%. Yield above 6% at a regulated utility often signals a perceived dividend-cut risk.", "Yield = Annual Dividends / Price", "valuation")
_add("earnings_yield", "Earnings Yield", "Inverse of P/E ratio.", "Compare to 10-year bond yields for rate-sensitive utilities. The spread is a first-order driver of the sector multiple.", "Earnings Yield = EPS / Price", "valuation")
_add("price_to_tangible_book", "Price / Tangible Book", "Price vs tangible book value per share.", "Close proxy for P/Rate Base on regulated names. 1.5-2.5x is typical; higher multiples reflect rate-base-growth quality.", "P/TBV = Price / (Equity - Intangibles) / Shares", "valuation")
_add("price_to_ncav", "Price / NCAV (Net-Net)", "Price vs net current asset value per share.", "Rarely meaningful for utilities — the asset base is dominated by long-lived PP&E, not working capital. Hidden in most utility reports.", "P/NCAV = Price / (Current Assets - Total Liabilities) / Shares", "valuation")
_add("cash_to_market_cap", "Cash-to-Market-Cap Ratio", "How much of market cap is backed by cash.", "Usually very low at operating utilities (cash is reinvested in rate base). A high ratio may indicate a non-operating holding or a recently-divested subsidiary.", "Cash / Market Cap = Total Cash / Market Capitalization", "valuation")
_add("ev_per_boe", "EV per BOE of Reserves", "Legacy energy-sector metric. Not populated for utilities.", "Preserved for Lince suite schema parity. Utilities use P/Rate Base and EV/EBITDA as the equivalent asset-based anchors.", "EV / Total Proved Reserves (BOE)", "valuation")
_add("ev_per_mcfe", "EV per MCFE of Reserves", "Legacy energy-sector metric. Not populated for utilities.", "Preserved for Lince suite schema parity. For gas utilities, rate-base growth is the analogous metric.", "EV / Total Reserves (MCFE)", "valuation")
_add("p_nav", "Price / Rate Base (proxy)", "Market cap vs rate base for regulated utilities, or vs asset-based NAV for IPPs.", "Primary structural valuation anchor for regulated utilities. 1.5-2.2x signals a market premium on rate-base growth; below 1.3x suggests regulatory or credit stress.", "P/RB = Market Cap / Rate Base (or NPV of long-term contracted cash flows)", "valuation")

# Profitability
_add("roe", "Return on Equity", "Profit generated per dollar of equity.", "Central utility metric — compare directly to the allowed ROE from the most recent rate case. A 50-150bps gap below allowed is normal (regulatory lag); a wider gap suggests execution or regulatory issues.", "ROE = Net Income / Equity", "profitability")
_add("roa", "Return on Assets", "Profit per dollar of assets.", "Low at utilities (3-5%) because of heavy asset base. Useful for comparing operating efficiency across similar business models.", "ROA = Net Income / Total Assets", "profitability")
_add("roic", "Return on Invested Capital", "Return on all invested capital.", "At regulated utilities, should track the weighted cost of capital used by regulators. Persistent ROIC >8% indicates better-than-allowed operational efficiency.", "ROIC = NOPAT / Invested Capital", "profitability")
_add("gross_margin", "Gross Margin", "Revenue remaining after cost of goods sold.", "Distorted by fuel / purchased-power pass-throughs. Use EBITDA margin or operating margin as the preferred efficiency read.", "Gross Margin = Gross Profit / Revenue", "profitability")
_add("operating_margin", "Operating Margin", "Revenue remaining after all operating expenses.", "Useful cross-check on cost discipline. Regulated utilities 15-25%; IPPs vary widely with fuel mix.", "Operating Margin = Operating Income / Revenue", "profitability")
_add("net_margin", "Net Profit Margin", "Revenue remaining as net profit.", "Regulated utilities typically 8-12%. Lower margins can be artifacts of pass-through revenue rather than underperformance.", "Net Margin = Net Income / Revenue", "profitability")
_add("fcf_margin", "Free Cash Flow Margin", "Revenue converted to free cash flow.", "Often negative at rate-base-growth utilities because capex exceeds OCF. Track direction over a full rate-case cycle rather than the point-in-time level.", "FCF Margin = FCF / Revenue", "profitability")
_add("ebitda_margin", "EBITDA Margin", "Revenue remaining as EBITDA.", "Preferred profitability read for utilities. Regulated electric 30-40%; regulated gas 25-35%; IPPs 20-30%; water 45-55%.", "EBITDA Margin = EBITDA / Revenue", "profitability")

# Solvency
_add("debt_to_equity", "Debt-to-Equity Ratio", "Debt financing vs equity financing.", "Utilities are among the most levered sectors. D/E of 1.0-1.5x is typical. The regulator-approved equity layer (usually 45-55%) is the effective constraint.", "D/E = Total Debt / Equity", "solvency")
_add("current_ratio", "Current Ratio", "Short-term asset coverage of liabilities.", "Often <1 at utilities because of reliance on revolvers and commercial paper. Not a red flag in isolation; read alongside FFO/Debt and credit ratings.", "Current Ratio = Current Assets / Current Liabilities", "solvency")
_add("quick_ratio", "Quick Ratio", "Liquidity excluding inventory.", "Of modest use at utilities. Short-term liquidity is driven by revolver headroom, not working capital.", "Quick Ratio = (Current Assets - Inventory) / Current Liabilities", "solvency")
_add("interest_coverage", "Interest Coverage", "Ability to pay interest from operating earnings.", "Should exceed 2.5-3.0x at investment-grade utilities. Below 2.0x risks a downgrade and higher all-in cost of capital.", "Interest Coverage = Operating Income / Interest Expense", "solvency")
_add("altman_z_score", "Altman Z-Score", "Bankruptcy probability predictor.", "Weakened for utilities because of structural high leverage. Rely more on FFO/Debt and credit rating outlook for utility solvency.", "Z = 1.2(WC/TA) + 1.4(RE/TA) + 3.3(EBIT/TA) + 0.6(MV/TL) + 1.0(Sales/TA)", "solvency")
_add("cash_burn_rate", "Cash Burn Rate", "Annual rate of cash consumption.", "Critical for pre-operational utility developers (GW in construction with no cash-flowing assets yet). Not meaningful for mature operators.", "Cash Burn = Annual Operating Cash Flow (when negative)", "solvency")
_add("cash_runway_years", "Cash Runway", "Years of operation at current burn rate.", "For pre-operational developers only. A runway below 18 months signals imminent equity or project-level financing need.", "Cash Runway = Total Cash / Annual Burn Rate", "solvency")
_add("ncav_per_share", "NCAV Per Share", "Net current asset value per share.", "Essentially non-informative for utilities — assets are long-lived PP&E, not current assets. Included for cross-suite consistency.", "NCAV/Share = (Current Assets - Total Liabilities) / Shares", "solvency")
_add("burn_as_pct_of_market_cap", "Burn Rate % of Market Cap", "How fast the company consumes value.", "Applied only to pre-operational utility developers. >8% annually in the pre-revenue stage points to concentrated near-term financing risk.", "Burn % = |Annual Burn Rate| / Market Cap", "solvency")

# Growth
_add("revenue_growth_yoy", "Revenue Growth (YoY)", "Annual revenue change.", "Heavily distorted by fuel pass-through, weather and M&A. Look at rate-base growth or customer-count growth for the underlying trend.", "Growth = (Rev_Current - Rev_Prior) / |Rev_Prior|", "growth")
_add("revenue_cagr_3y", "Revenue CAGR (3-Year)", "3-year compound revenue growth.", "Smooths weather and fuel swings. Above 5% is strong for a regulated utility; above 8% is exceptional.", "CAGR = (End/Start)^(1/3) - 1", "growth")
_add("earnings_growth_yoy", "Earnings Growth (YoY)", "Annual net income change.", "Regulated utilities target 5-8% EPS CAGR through rate-base growth. Anything above 9% usually incorporates M&A or one-off regulatory wins.", "Growth = (NI_Current - NI_Prior) / |NI_Prior|", "growth")
_add("shares_growth_yoy", "Share Dilution (YoY)", "Annual change in shares outstanding.", "Utilities fund ~20-30% of capex with equity. 2-5% annual dilution is normal; above 6% can erode per-share growth, especially when equity is issued below book value.", "Dilution = (Shares_Current - Shares_Prior) / Shares_Prior", "growth")
_add("shares_growth_3y_cagr", "Dilution CAGR (3-Year)", "3-year compound share dilution rate.", "Persistent >5% dilution materially offsets rate-base growth on a per-share basis. Check DRIP / ATM offering cadence.", "CAGR = (Shares_End / Shares_Start)^(1/3) - 1", "growth")
_add("quality_score", "Utility Quality Score", "Composite quality score (0-100).", "Evaluates regulatory jurisdiction quality, rate-base growth trajectory, earned-vs-allowed ROE gap, financial position, and dividend sustainability. Weights adapt by stage. >70 is high quality, <30 is weak.", "Weighted sum of: regulatory quality, rate-base growth, ROE gap, FFO/Debt, dividend coverage, revenue stability", "energy_quality")

# Utilities capital discipline & cash flow metrics
_add("fcf_yield", "FCF Yield", "Free cash flow as percentage of enterprise value.", "Often low or negative at rate-base-growth utilities because capex >> OCF. A sustained positive FCF yield >5% signals harvesting mode rather than growth.", "FCF Yield = Free Cash Flow / Enterprise Value", "valuation")
_add("croci", "Cash Return on Capital Invested", "Operating cash flow as return on invested capital.", "Useful cross-check against reported ROIC. At regulated utilities CROCI 6-9% is healthy; lower values suggest regulatory lag or weak cost recovery.", "CROCI = Operating Cash Flow / (Total Assets - Cash)", "profitability")
_add("ocf_to_net_income", "OCF / Net Income Ratio", "How much of reported earnings converts to actual cash.", "Should consistently exceed 1.5x at utilities (depreciation is large). A ratio below 1.0 suggests aggressive revenue recognition (e.g. accrued regulatory assets) and warrants scrutiny.", "OCF/NI = Operating Cash Flow / |Net Income|", "profitability")
_add("debt_per_share", "Debt Per Share", "Total debt burden allocated per share.", "Meaningful at utilities given high leverage. Track trend alongside book-value / rate-base per share — debt should grow no faster than rate base.", "Debt/Share = Total Debt / Shares Outstanding", "solvency")
_add("debt_service_coverage", "Debt Service Coverage (FFO Proxy)", "Ability to service debt from operating cash flow.", "The practical read of FFO interest coverage for utilities. >4x is investment-grade; 2.5-4x is acceptable; <2.5x threatens the rating.", "DSC = Operating Cash Flow / Interest Expense", "solvency")
_add("capex_to_revenue", "Capex / Revenue", "Capital expenditure as percentage of revenue.", "Very high for utilities by design. 15-30% is normal; >35% signals a heavy rate-base-growth cycle (and corresponding equity issuance needs).", "Capex % = |Capital Expenditure| / Revenue", "growth")
_add("capex_to_ocf", "Capex / Operating Cash Flow", "Capital spending relative to cash generation.", "Commonly >100% at rate-base-growth utilities — the gap is funded with debt and equity. Sustainability check: gap must fit within credit metrics and equity issuance cadence.", "Capex/OCF = |Capital Expenditure| / Operating Cash Flow", "growth")
_add("reinvestment_rate", "Reinvestment Rate (Capex / EBITDA)", "Capital expenditure as percentage of EBITDA.", "Regulated utilities frequently reinvest 80-120% of EBITDA. Below 60% indicates harvesting / low growth; above 130% stresses credit metrics absent tariff catch-up.", "Reinvestment = |Capex| / EBITDA", "growth")
_add("dividend_payout_ratio", "Dividend Payout Ratio", "Percentage of net income paid as dividends.", "Utilities commonly target 60-75% of earnings. Above 85% in the regulated segment signals limited reinvestment; below 50% is usually a growth utility funding rate-base expansion.", "Payout = |Dividends| / Net Income", "growth")
_add("dividend_coverage", "Dividend Coverage (FCF)", "How many times FCF covers the dividend.", "Often <1x at growth utilities (dividend funded partly by debt / equity). A more relevant read is OCF-based coverage; <1x long-term signals cut risk for mature utilities.", "Coverage = Free Cash Flow / |Dividends Paid|", "growth")
_add("shareholder_yield", "Shareholder Yield", "Total cash returned to shareholders as percentage of market cap.", "Less relevant for growth utilities that issue equity to fund capex. More useful at mature IPPs / YieldCos where buybacks supplement dividends.", "Yield = (Dividends + Buybacks) / Market Cap", "growth")
_add("fcf_per_share", "FCF Per Share", "Free cash flow allocated per share.", "Often negative for rate-base-growth utilities. Track trend over multiple years and across rate-case cycles rather than point-in-time levels.", "FCF/Share = Free Cash Flow / Shares Outstanding", "growth")
_add("ocf_per_share", "OCF Per Share", "Operating cash flow allocated per share.", "Better per-share cash-generation read than FCF for utilities. Rising OCF/share is the cleanest indicator of improving operating efficiency and cost recovery.", "OCF/Share = Operating Cash Flow / Shares Outstanding", "growth")
_add("fcf_conversion", "FCF / EBITDA Conversion", "How efficiently EBITDA converts to free cash flow.", "Typically low for utilities (often <20%) because capex absorbs operating cash. Rising conversion over a rate-case cycle is a bullish signal.", "FCF Conversion = Free Cash Flow / EBITDA", "efficiency")
_add("capex_intensity", "Capex Intensity", "Capital expenditure as share of revenue.", "Utilities are structurally capex-heavy (15-30%+). Compare within sub-sector: water highest, IPPs lowest once operational.", "Intensity = |Capex| / Revenue", "efficiency")

SECTION_EXPLANATIONS = {
    "profile": {"title": "Company Profile", "description": "Company identification, market cap tier, utility development stage, primary service type, and regulatory-jurisdiction classification."},
    "valuation": {"title": "Valuation Metrics", "description": "Price-based ratios including traditional metrics and utility-specific anchors (P/Rate Base, dividend yield, EV/EBITDA). Regulated utilities anchor to P/RB and dividend yield; IPPs to EV/EBITDA."},
    "profitability": {"title": "Profitability Metrics", "description": "Margin and return analysis. At regulated utilities, earned ROE should be compared directly to the allowed ROE from the last rate case. Fuel-cost pass-through distorts gross margin."},
    "solvency": {"title": "Solvency & Credit", "description": "Balance sheet strength and credit metrics. Utilities are structurally leveraged; investment-grade ratings (FFO/Debt >14%) are the standard. Interest coverage, debt/EBITDA and FFO metrics drive agency views."},
    "growth": {"title": "Growth & Capital Allocation", "description": "Revenue, earnings and share count trends. Rate-base-growth utilities typically issue 2-5% equity annually to fund capex; watch that EPS and DPS growth outpace share issuance."},
    "share_structure": {"title": "Share Structure", "description": "Analysis of outstanding shares, insider ownership, institutional holdings and equity-issuance programs. Utility insider ownership is usually low; strong institutional sponsorship is the norm."},
    "energy_quality": {"title": "Utilities Quality Assessment", "description": "Stage-appropriate quality scoring. Evaluates regulatory jurisdiction, rate-base growth, earned-vs-allowed ROE gap, dividend coverage, and financial position. Replaces traditional moat analysis with utility-specific regulatory factors."},
    "intrinsic_value": {"title": "Intrinsic Value Estimates", "description": "Multiple valuation methods adapted by stage. Operating utilities: DCF / dividend-discount. Developers: P/NAV of contracted pipeline. Early-stage developers: cash backing plus pipeline NPV."},
    "conclusion": {"title": "Assessment Conclusion", "description": "Weighted scoring across 5 categories with weights adapted by both tier and stage. Includes a screening checklist evaluating key quality criteria for utility companies."},
}

CONCLUSION_METHODOLOGY = {
    "overall": {"title": "Conclusion Methodology", "description": "Score is a weighted average of 5 categories (valuation, profitability, solvency, growth, utility quality). Weights vary by BOTH company tier AND development stage. Pre-operational developers weight solvency at 35-40% and utility quality at 30-35%. Operating utilities use more balanced weights with heavier emphasis on profitability and growth. Verdicts: Strong Buy (>=75), Buy (>=60), Hold (>=45), Caution (>=30), Avoid (<30)."},
    "valuation": {"title": "Valuation Score", "description": "Starts at 50. Adjusted by P/E, P/B (rate-base proxy), dividend yield, EV/EBITDA, and FCF yield where meaningful. Pre-revenue metrics are excluded for early-stage developers."},
    "solvency": {"title": "Solvency Score", "description": "Starts at 50. Debt/equity, debt/EBITDA, interest coverage, and credit-quality proxies. Pre-operational developers are penalized heavily for any debt taken before cash-flowing assets exist. Cash runway <1 year = -25 points."},
    "energy_quality": {"title": "Utility Quality Score", "description": "Composite of regulatory jurisdiction (25pts), rate-base growth / financial position (25pts), earned-vs-allowed ROE gap (20pts), dividend coverage (15pts), and revenue predictability (15pts)."},
}

def get_explanation(key): return METRIC_EXPLANATIONS.get(key)
def get_section_explanation(section): return SECTION_EXPLANATIONS.get(section)
def get_conclusion_explanation(category=None): return CONCLUSION_METHODOLOGY.get(category or "overall")
def list_metrics(category=None):
    metrics = list(METRIC_EXPLANATIONS.values())
    return [m for m in metrics if m.category == category] if category else metrics
